- job:
    name: otc-tox-py39-tips
    parent: otc-tox-py39
    description: |
      Execute tests with latest dependencies
    required-projects:
      - name: opentelekomcloud/python-otcextensions
        override-checkout: elb

- project:
    merge-mode: squash-merge
    default-branch: main
    templates:
      - publish-otc-docs-pti
      - release-notes-jobs
    check:
      jobs:
        - otc-tox-pep8
        - otc-tox-py39-tips
    gate:
      jobs:
        - otc-tox-pep8
        - otc-tox-py39-tips
